@php
	if(isset($item['item'])) {
		$item = $item['item'];
	}
@endphp

@if($item->comment_rate == 0)
	@include('svg.star_3')
	@include('svg.star_3')
	@include('svg.star_3')
	@include('svg.star_3')
	@include('svg.star_3')
@elseif($item->comment_rate > 0 && $item->comment_rate <= 10)
	@include('svg.star_2')
	@include('svg.star_3')
	@include('svg.star_3')
	@include('svg.star_3')
	@include('svg.star_3')
@elseif($item->comment_rate > 10 && $item->comment_rate <= 20)
	@include('svg.star_1')
	@include('svg.star_3')
	@include('svg.star_3')
	@include('svg.star_3')
	@include('svg.star_3')
@elseif($item->comment_rate > 20 && $item->comment_rate <= 30)
	@include('svg.star_1')
	@include('svg.star_2')
	@include('svg.star_3')
	@include('svg.star_3')
	@include('svg.star_3')
@elseif($item->comment_rate > 30 && $item->comment_rate <= 40)
	@include('svg.star_1')
	@include('svg.star_1')
	@include('svg.star_3')
	@include('svg.star_3')
	@include('svg.star_3')
@elseif($item->comment_rate > 40 && $item->comment_rate <= 50)
	@include('svg.star_1')
	@include('svg.star_1')
	@include('svg.star_2')
	@include('svg.star_3')
	@include('svg.star_3')
@elseif($item->comment_rate > 50 && $item->comment_rate <= 60)
	@include('svg.star_1')
	@include('svg.star_1')
	@include('svg.star_1')
	@include('svg.star_3')
	@include('svg.star_3')
@elseif($item->comment_rate > 60 && $item->comment_rate <= 70)
	@include('svg.star_1')
	@include('svg.star_1')
	@include('svg.star_1')
	@include('svg.star_2')
	@include('svg.star_3')
@elseif($item->comment_rate > 70 && $item->comment_rate <= 80)
	@include('svg.star_1')
	@include('svg.star_1')
	@include('svg.star_1')
	@include('svg.star_1')
	@include('svg.star_3')
@elseif($item->comment_rate > 80 && $item->comment_rate <= 90)
	@include('svg.star_1')
	@include('svg.star_1')
	@include('svg.star_1')
	@include('svg.star_1')
	@include('svg.star_2')
@else
	@include('svg.star_1')
	@include('svg.star_1')
	@include('svg.star_1')
	@include('svg.star_1')
	@include('svg.star_1')
@endif